spring:
  datasource:
    master:
      jdbcUrl: jdbc:postgresql://127.0.0.1:15432/medicine
      username: postgres
      password: 123
      driverClassName: org.postgresql.Driver
      maximumPoolSize: 80
      maxLifetime: 18000
    slave:
      jdbcUrl: jdbc:postgresql://127.0.0.1:25432/medicine
      username: postgres
      password: 123
      driverClassName: org.postgresql.Driver
      maximumPoolSize: 80
      maxLifetime: 18000
    config:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: true
  #  https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-369388646
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

auth:
  admin:
    token:
      expire: 3600

aliyun:
  email:
    region: cn-hangzhou
    accessKey: accessKey
    accessSecret: accessSecret

redis:
  host: localhost
  port: 56379

