spring:
  datasource:
    master:
      jdbcUrl: jdbc:mysql://127.0.0.1:13306/medicine?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
    slave:
      jdbcUrl: jdbc:mysql://127.0.0.1:13306/medicine?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

auth:
  admin:
    token:
      expire: 3600

redis:
  host: localhost
  port: 16379
  database: 0