spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/medicine
    username: postgres
    password: 123

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

auth:
  admin:
    token:
      expire: 3600

aliyun:
  email:
    region: cn-hangzhou
    accessKey: accessKey
    accessSecret: accessSecret

redis:
  host: localhost
  port: 56379
