spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/medicine
    username: postgres
    password: 123

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

aliyun:
  email:
    region: cn-hangzhou
    accessKey: accessKey
    accessSecret: accessSecret
