version: '3'
services:

  postgres:
    image: postgres:10.1
    container_name: medicine-postgres
    ports:
    - "55432:5432"
    environment:
    - POSTGRES_PASSWORD=123

  redis:
    image: redis:5
    container_name: medicine-redis
    ports:
    - "56379:6379"
