version: "3.5"
services:
  mysql:
    image: mysql:8.0
    container_name: medicine-mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 13306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

  redis:
    image: redis:6.2.3
    container_name: medicine-redis
    ports:
      - 16379:6379

  openldap:
    image: osixia/openldap:1.2.3
    container_name: medicine-openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_TLS=false
      - LDAP_DOMAIN=pjhu.org  # cn=admin,dc=pjhu,dc=org
      - LDAP_ADMIN_PASSWORD=123

  phpldapadmin:
    image: osixia/phpldapadmin:0.7.2
    container_name: medicine-phpldapadmin
    ports:
      - "5443:443"
      - "5080:80"
    environment:
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_HOSTS=openldap # must be ldap service name
      - PHPLDAPADMIN_SERVER_PATH=/phpldapadmin
    links:
      - openldap

