version: '3'
services:
  postgres-master:
    image: postgres-test:11.2
    build: .
    container_name: medicine-postgres-master
    ports:
      - 15432:5432
    environment:
      PG_ROLE: master
      POSTGRES_PASSWORD: 123
  postgres-slave:
    image: postgres-test:1.0
    container_name: medicine-postgres-slave
    ports:
      - 25432:5432
    depends_on:
      - postgres-master
    environment:
      PG_ROLE: slave
      PG_MASTER_SERVICE_HOST: postgres-master

  redis:
    image: redis:5
    container_name: medicine-redis
    ports:
      - "56379:6379"

  openldap:
    image: osixia/openldap:1.2.3
    container_name: medicine-openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_TLS=false
      - LDAP_DOMAIN=pjhu.org  # cn=admin,dc=pjhu,dc=org
      - LDAP_ADMIN_PASSWORD=123

  phpldapadmin:
    image: osixia/phpldapadmin:0.7.2
    container_name: medicine-phpldapadmin
    ports:
      - "5443:443"
      - "5080:80"
    environment:
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_HOSTS=openldap # must be ldap service name
      - PHPLDAPADMIN_SERVER_PATH=/phpldapadmin
    links:
      - openldap

